INSERT INTO TAB_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES ('1', 'jw', 'password');
INSERT INTO TAB_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES ('2', 'moderator', 'moderator');
INSERT INTO TAB_USER(USER_ID, USER_NAME, USER_PASSWORD) VALUES ('3', 'follower', 'follower');

INSERT INTO TAB_USER_ROLE(USER_ID, USER_ROLE) VALUES ('1', 'USER');
INSERT INTO TAB_USER_ROLE(USER_ID, USER_ROLE) VALUES ('2', 'MODERATOR');
INSERT INTO TAB_USER_ROLE(USER_ID, USER_ROLE) VALUES ('3', 'USER');